backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "Posts"
    format: "json"
    folder: "assets/content/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Tipologia", name: "type", widget: "select", options: ["dolce", "salato"], required: true }
      - { label: "Immagine", name: "thumbnail", widget: "string" }
