backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    format: "json"
    folder: "assets/content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Tipologia", name: "type", widget: "select", options: ["dolce", "salato"] }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
